### PR TITLE
fix: Owner requirement boolean parsing from string

### PR DESCRIPTION
**Pull request by Tiboris**
When parsing boolean values from string using bool() builtin funtion string which is not empty returns True Writing a util function to convert such strings
to proper boolean values. NOTE: distutil implementation: from distutils.util import strtobool
will be deprecated and removed in future python releases thus implementing a funtion ourselves might be
future proof solution at this time.

Signed-off-by: Tibor Dudlák <tdudlak@redhat.com>

### CODE REVIEW

**Comment by pvoborni** [comment]
`value_to_bool` looks like, that it is a perfect candidate for a unit test ;)

**Comment by Tiboris** [comment]
I thought that when affected mrack util unit tests were not wrapped by Class It caused that they were not run. 
The old run of pytest:

https://dev.azure.com/neoave/mrack/_build/results?buildId=816&view=logs&j=27008f10-b491-547d-a654-20cfee07d03e&t=73113a39-43fd-502e-b4fb-b68667aceda6&l=330

```
======================= 81 passed, 22 warnings in 1.32s ========================
```

Adding the class and waiting for new run.

@miskopo Could you try to help me find what I am missing?

**Comment by kaleemsiddiqu** [comment]
Though not related with this but we should one test for osp env as well like for get_username(host_win_aws, metahost_win, provisioning_config)
Rest LGTM

**Review by kaleemsiddiqu — APPROVED** [review]

**Comment by Tiboris** [comment]
Thanks for review !

**Pull request merged**
