### PR TITLE
feat: Add translantion for kernel_options and kernel_options_post

### PR DESCRIPTION
**Pull request by skycastlelily**

### CODE REVIEW

**Comment by dav-pascual** [comment]
Hi @skycastlelily, changes look good. 
Could you please fix the flake8 warnings?

**Comment by skycastlelily** [comment]
Sure,updated,thanks for your review:)

**Comment by Tiboris** [comment]
@skycastlelily Hello, please see https://github.com/neoave/mrack/actions/runs/11395400988/job/31720359590?pr=299 for more small issues in a code. Also i think @dav-pascual woudl welcome the fixes to be included in first commit.

**Comment by skycastlelily** [comment]
Thanks for pointing that out.
Sorry, obviously I  forgot to run pre-commit locally.
I made the summary shorter but clear enough,I ran pre-commit locally this
time, should be good now:)

**Comment by dav-pascual** [comment]
@skycastlelily test_beaker_transformer is failing. https://dev.azure.com/neoave/mrack/_build/results?buildId=1185&view=logs&jobId=e4354d11-29aa-59c2-ce04-0d9aced3ea05&j=e4354d11-29aa-59c2-ce04-0d9aced3ea05&t=c546a923-41d2-519e-602b-c74183bf4a4c 

Please, could you run pytest locally?

**Comment by skycastlelily** [comment]
Hi,sorry for the late reply, I was pretty busy with other stuff, I ran
pytest locally before I submitted this mr,it did fail, but after I git
checkout main, it also failed, as follows,so I submitted the mr.
FAILED
tests/unit/test_beaker_transformer.py::TestBeakerTransformer::test_beaker_requirement[meta_host2-exp_values2]
- AssertionError: Mismatch of transformed value and expected value[tasks]:
[{'name': '/distribution/dummy', 'role': 'STANDALONE'}] != [{'name':
'/distribution/dummy', 'role': 'STANDALONE', 'params':
['RSTRNT_DISABLED=10_avc_check']}]

I looked into the README of mrack, and run tox locally, main branch pass,
this mr failed.
Anyway, update this mr with the problem fixed, tox check pass locally , so
I guess we are finally really good now:)

**Comment by dav-pascual** [comment]
@skycastlelily Sorry for the late reply. All good, thank you :)

**Review by dav-pascual — APPROVED** [review]

**Pull request merged**
