### PR TITLE
fix: Update spec to match fedora community standard

### PR DESCRIPTION
**Pull request by Tiboris**
Update the mrack specfile to match fedora packaging standars and to move this project to official fedora packages via: https://bugzilla.redhat.com/show_bug.cgi?id=2134387

Signed-off-by: Tibor Dudlák <tdudlak@redhat.com>

### CODE REVIEW

**Review by netoarmando — APPROVED** [review]
Changes look good to me. Only thing: there is a typo in the commit title and message ("comunity" and "standars").

**Comment by Tiboris** [comment]
Thanks @netoarmando for review i will update it!

**Comment by Tiboris** [comment]
Second commit adds CHANGELOG.md file to python package tarball which is later used by specfile to build.

**Review by dav-pascual — APPROVED** [review]
Thanks for the patch! LGTM @Tiboris

**Pull request merged**
