### PR TITLE
feat: handle list value for add_dict_to_node function

### PR DESCRIPTION
**Pull request by skycastlelily**
fix this issue:https://github.com/neoave/mrack/issues/291 :)

### CODE REVIEW

**Comment by pvoborni** [comment]
Hi, could you also add  a unit test that verifies that the use case in #291 works? That the resulting xml is as expected and that the beaker client accepts it.

**Comment by skycastlelily** [comment]
Updated,Sorry for the late reply,I was on National holiday again,it's
outing season here:)

**Review by pvoborni — COMMENTED** [review]
the code LGTM, but please fix the lint issues highlighted by CI:

- title of the test commit
- flake8 check https://dev.azure.com/neoave/mrack/_build/results?buildId=1153&view=logs&jobId=e4354d11-29aa-59c2-ce04-0d9aced3ea05&j=e4354d11-29aa-59c2-ce04-0d9aced3ea05&t=37a28340-749f-5255-d3d8-b83a7b4239ca

**Comment by skycastlelily** [comment]
Sure,updated:)

**Review by pvoborni — APPROVED** [review]
Now, holidays and PTO were on my side :) .

Thanks for the change. LGTM.

**Comment by skycastlelily** [comment]
Thanks:)

**Pull request merged**
