### PR TITLE
fix(Beaker): connection to hub timing out

### PR DESCRIPTION
**Pull request by Tiboris**
mrack was failing with an exception when
Beaker hub was not replying to requests for
some time. With this we accept the fact that
hub may not respond and we use previous
result and continue the wait for resource.

Signed-off-by: Tibor Dudlák <tdudlak@redhat.com>

### CODE REVIEW

**Review by XiyangDong — COMMENTED** [review]
Looks good to me, shall we quickly test that the change does not break beaker provisioning?

**Comment by Tiboris** [comment]
Let me re-base and run something.

**Comment by XiyangDong** [comment]
I am ok with merging this if @dav-pascual is also in favor of that.

**Review by dav-pascual — APPROVED** [review]

**Comment by dav-pascual** [comment]
Fine by me as well!

**Pull request merged**
