### PR TITLE
fix: Translate job-group properly

### PR DESCRIPTION
**Pull request by skycastlelily**

### CODE REVIEW

**Comment by skycastlelily** [comment]
Block  tmt mr: https://github.com/teemtee/tmt/pull/3397 :)

**Comment by skycastlelily** [comment]
Hi Dav, thanks for your review, I have updated the commit message, I guess we are good now, and sorry for failing to note that before I submit this mr :sweat_smile:

**Comment by dav-pascual** [comment]
Hi @skycastlelily 
Thank you for your changes. In principle LGTM.
The reason behind this change is that previous key was wrong, right?

**Comment by skycastlelily** [comment]
> The reason behind this change is that previous key was wrong, right?

Yes ,
BeakerJob use job-group key instead of group.
I have moved the above line here,hope we can get rid of the PR header format error:)

**Comment by dav-pascual** [comment]
LGTM. Nevermind about the failing check, idk why it's still failing

**Pull request merged**
